version: '3'
services:
  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: dataside_apii
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3002:3002
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dataside_db
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./dataside_script.sql:/docker-entrypoint-initdb.d/dataside_script.sql
